version: '2.4'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./qrcodes:/app/qrcodes
    environment:
      - FLASK_ENV=production
      - BASE_URL=${BASE_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
